export component Enemy inherits Rectangle {
    in property <float> speed: 1.0;
    in property <float> scale: 1.0;

    in-out property <float> position_x: 0.0;
    in property <bool> game_over: false;   

    x: position_x * 1px;

    width: 60px * scale;
    height: 40px * scale;
    background: transparent;

    border-color: blue;    
    border-width: 2px * scale;

    Rectangle {
        Image {
            width: 100%;
            height: 100%;
            source: @image-url("../../assets/img/cuy.png");
        }
    }

    Timer {
        interval: 16ms;
        running: !root.game_over;  
        triggered => {
            position_x -= speed * 2;
        }
    }
}
