export component Game_window inherits Rectangle {
    in-out property <int> score: 0;
    in-out property <int> time: 0;
    in property <float> scale: 1.0;

    property <int> frame: 0;

    VerticalLayout {

        alignment: center;

        HorizontalLayout {
            alignment: center;
            Rectangle {
                border-color: black;
                border-width: 2px;
                background: #D9D9D9;
                width: 970px * scale;
                border-radius: 10px;
                height: 480px * scale;
                clip: true;

                HorizontalLayout {
                    spacing: parent.width * 0.001;
                    padding: 30px * scale;
                    alignment: space-between;

                    Text {
                        text: "Score: \{score}";
                        color: #37383F;
                        font-family: "Minecraft";
                        font-size: 20px;
                    }

                    Text {
                        text: "Timer: \{time}";
                        color: #37383F;
                        font-family: "Minecraft";
                        font-size: 20px;
                    }
                }

                Rectangle {
                    width: parent.width;
                    height: 70%;
                    y: parent.height - self.height;

                    Image {
                        source: @image-url("../../assets/img/background.png");
                        width: parent.width;
                        height: parent.height;
                    }
                }

                Timer {
                    interval: 400ms;
                    running: true;
                    triggered => {
                        frame = Math.mod(frame + 1, 2);
                    }
                }

                Rectangle {

                    width: parent.width * 0.1;
                    height: 40%;
                    y: parent.height - self.height - parent.height * 0.05;
                    x: parent.width * 0.1;

                    Image {
                        width: parent.width;
                        height: parent.height;
                        image-fit: contain;
                        source: {
                            if frame == 1 {
                                @image-url("../../assets/img/h2.png");
                            } else {
                                @image-url("../../assets/img/h4.png");
                            }
                        }
                    }
                }
            }
        }
    }
}
