export component MainCharacter inherits Rectangle {
    
    //callbacks
    in-out property <bool> is_jumping: false;
    in-out property <bool> jump_triggered: false;

    in property <float> scale: 1.0;
    in property <int> frame: 0;
    in-out property <bool> has_focus: true;

    in property <length> ground_y: 480px * 0.55;
    in property <length> jump_y: 480px * 0.05;

    in property <length> character_height: 100px;
    in property <length> character_width: 100px;

    in property <bool> game_over: false;

    width: 55px * scale;
    height: 100px * scale;
    y: is_jumping ? jump_y * scale : ground_y * scale;
    x: root.width * 2;

    border-color: red;
    border-width: 2px * scale;

    animate y {
        duration: 650ms;
        easing: ease-out;
    }

    ground_check := Timer {
        interval: 20ms;
        running: true;
        triggered => {
            if (root.is_jumping && Math.abs(root.y - (root.jump_y * root.scale)) < 1px) {
                root.is_jumping = false;
            }
        }
    }

    Image {
        width: parent.width;
        height: parent.height;
        image-fit: contain;
        source: {
            if frame == 1 {
                @image-url("../../assets/img/h2.png");
            } else {
                @image-url("../../assets/img/h4.png");
            }
        }
    }

    focus-timer := Timer {
        interval: 10ms;
        running: true;
        triggered => {
            my-key-handler.focus();
        }
    }

    forward-focus: my-key-handler;

    my-key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == " " && !root.game_over && !root.is_jumping && !root.jump_triggered && Math.abs(root.y - (root.ground_y * root.scale)) < 2px) {
                root.is_jumping = true;
                root.jump_triggered = true;
            }
            accept
        }

        key-released(event) => {
            if (event.text == " ") {
                root.jump_triggered = false;
            }
            accept
        }
    }
}
