[package]
name = "naback-deskop"
version = "0.1.0"
edition = "2024"

[dependencies]

egui = "0.32.0"
egui_extras = { version = "0.32.0", features = ["image"] }

eframe = "0.32.0"

env_logger = { version = "0.11.8", default-features = false, features = [
    "auto-color",
    "humantime",
] }