import "../assets/font/Minecraft.ttf";

export component MainWindow inherits Window {
    Text {
        text: "¡Elige uno!";
        color: #37383F;
        font-size: 70px ;
        font-family: "Minecraft";
        height: 95%;
    }

    Rectangle {
        border-radius: 30px;
        width: parent.width * 0.8;
        height: parent.height * 0.75;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height)/ 2 + 20px;
        clip : true;

            Image {
            source: @image-url("../assets/img/fondo_general.png");
            width: parent.width;
            height: parent.height;}
    }

}