import {Background} from "background.slint";
import {TextEdit} from "std-widgets.slint";
import { ArrowHeader } from "components/buttons.slint";
import { home_button } from "components/home.slint";

export component Cards inherits Background {

    callback go_to_game();
    callback go_to_home();

    ArrowHeader {
        y: root.height * 0.019;
        scale: root.height / 750px;
        title: "¡Empezar!";
        show_right: false;
        go_left => {
            go_to_game();
        }
    }

    home-button {
        scale: root.height / 850px;
        x: root.width - self.width - root.width * 0.09;
        y: root.height * 0.020;

        go_home => {
            go_to_home()
        }
    }

    HorizontalLayout {
        alignment: center;
        spacing: (parent.height - self.height);
        Rectangle {
            clip: true;
            height: parent.height * 0.8;
            width: parent.width * 0.3;

            y: ((parent.height - self.height) / 2) * 1.6;

            Image {
                height: parent.height;
                width: parent.width;
                source: @image-url("../assets/img/cuadro.png");
            }

            Rectangle {
                height: parent.height * 0.75;
                width: parent.width * 0.7;
                background: black;
                TextEdit {
                    width: parent.width;
                    height: parent.height;
                    font-size: parent.height * 0.1;
                    text: "Hola arroba!";
                    wrap: word-wrap;
                }
            }
        }

        Rectangle {
            clip: true;
            height: parent.height * 0.8;
            width: parent.width * 0.3;
            y: ((parent.height - self.height) / 2) * 1.6;

            Image {
                source: @image-url("../assets/img/cuadro.png");
                height: parent.height;
                width: parent.width;
            }

            Rectangle {
                height: parent.height * 0.75;
                width: parent.width * 0.7;
                background: black;
                TextEdit {
                    width: parent.width;
                    height: parent.height;
                    font-size: parent.height * 0.1;
                    text: "Yaa 😿";
                    wrap: word-wrap;
                }
            }
        }

        Rectangle {
            clip: true;
            height: parent.height * 0.8;
            width: parent.width * 0.3;
            y: ((parent.height - self.height) / 2) * 1.6;
            Image {
                source: @image-url("../assets/img/cuadro.png");
                height: parent.height;
                width: parent.width;
            }

            Rectangle {
                height: parent.height * 0.75;
                width: parent.width * 0.7;
                background: black;
                TextEdit {
                    width: parent.width;
                    height: parent.height;
                    font-size: parent.height * 0.1;
                    text: "(Puedes editar cualquier carta)";
                    wrap: word-wrap;
                }
            }
        }
    }
}
