/*import {Background} from "background.slint";
import { Game } from "game.slint";
export component Game_w inherits Background {

    VerticalLayout {
        padding-top: root.height * 0.02;

        HorizontalLayout {
            alignment: center;
            spacing: root.width * 0.02;

            Rectangle {
                width: root.width * 0.09;
                height: root.height * 0.08;
                clip: true;

                Image {

                    height: parent.height;
                    width: parent.width;
                    source: @image-url("../assets/img/flecha_izquierda.png");
                }
            }

            Text {
                text: "¡Go!";
                color: #37383F;
                font-size: root.height * 0.08;
                font-family: "Minecraft";
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            Rectangle {
                width: root.width * 0.09;
                height: root.height * 0.08;
                Image {
                    height: parent.height;
                    width: parent.width;
                    source: @image-url("../assets/img/flecha_derecha.png");
                }
            }
        }
    }

    Rectangle {
        x: root.width - self.width - root.width * 0.09;
        y: root.height * 0.019;
        width: root.height * 0.09;
        height: root.height * 0.08;
        clip: true;

        Image {

            width: parent.width;
            height: parent.height;
            source: @image-url("../assets/img/home.png");
        }
    }

    @children
    Game {
        width: root.width * 0.9;
        height: root.height * 0.75;
        y: root.height * 0.12;
        scale: root.height / 400px;
    }
}
*/