import {Background} from "background.slint";

export component Game inherits Background {
    Text {
        text: "¡Go!";
        color: #37383F;
        font-size: 70px;
        font-family: "Minecraft";
        height: parent.height * 0.90;
    }

    VerticalLayout {

        padding-top: 30px;

        alignment: center;

        HorizontalLayout {
            alignment: center;
            Rectangle {

                border-color: black;
                border-width: 2px;
                background: #D9D9D9;
                width: parent.width * 0.9;
                border-radius: 10px;
                height: 80%;
                clip: true;

                Rectangle {
                    width: parent.width;
                    height: 70%;
                    y: parent.height - self.height;

                    Image {
                        source: @image-url("../assets/img/background.png");
                        width: parent.width;
                        height: parent.height;
                    }
                }
            }
        }
    }
}
