import {Background} from "background.slint";
import { ArrowHeader } from "components/buttons.slint";
import { Home_button } from "components/home.slint";
import { Game_window } from "components/game_window.slint";

export component Game inherits Background {
    in-out property <int> score: 0;
    in-out property <int> time: 0;
    in-out property <int> enemy_count: 0;
    in-out property <[float]> enemy_positions: [];
    
    in-out property <float> main_char_x;
    in-out property <float> main_char_y;
    in-out property <float> main_char_w;
    in-out property <float> main_char_h;

    callback go_to_cards();
    callback go_to_photos();
    callback go_to_home();
    callback spawn_enemy();
    callback set_enemy_positions([float]);

    ArrowHeader {
        y: root.height * 0.019;
        scale: root.height / 750px;
        title: "¡Go!";
        go_right => {
            go_to_cards();
        }

        go_left => {
            go_to_photos();
        }
    }

    Home-button {
        scale: root.height / 850px;
        x: root.width - self.width - root.width * 0.09;
        y: root.height * 0.020;
        go_home => {
            go_to_home();
        }
    }

    Game-window {
        x: root.width - self.width - root.width * 0.04;
        y: root.height * 0.035;
        score: root.score;
        time: root.time;
        scale: root.height / 650px;
        available_width: root.width * 0.95;
        enemy_count <=> root.enemy_count;
        enemy_positions <=> root.enemy_positions;
    }
}
