import { Menu } from "menu.slint";
import { Photos } from "photos.slint";
import { Cards } from "cards.slint";
import { Game } from "game.slint";

export { Menu, Photos, Cards , Game}

export component MainWrapper inherits Window {

    in-out property <int> current_page: 0;
    in-out property <int> score: 0;
    in-out property <int> time: 0;
    in-out property <int> enemy_count: 0;

    in-out property <bool> game_over: false;
    
    in-out property <float> main_char_x;
    in-out property <float> main_char_y;
    in-out property <float> main_char_w;
    in-out property <float> main_char_h;
    
    in-out property <[float]> enemy_positions: [];

    callback navigate_to_game_with_instance;
    callback set_enemy_positions(pos: [float]);

    set_enemy_positions(pos) => {
        root.enemy_positions = pos;
    }

    Menu {
        width: parent.width;
        height: parent.height;
        visible: root.current_page == 0;

        go_to_photos => {
            root.current_page = 1;
        }
        go_to_game => {
            root.current_page = 2;
            root.navigate_to_game_with_instance();
            root.set_enemy_positions([]);
        }

        go_to_cards => {
            root.current_page = 3;
        }
    }

    Photos {
        width: parent.width;
        height: parent.height;
        visible: root.current_page == 1;

        go_to_game => {
            root.current_page = 2;
            root.navigate_to_game_with_instance();
            root.set_enemy_positions([]);
        }

        go_to_home => {
            root.current_page = 0;
        }
    }

    if (root.current_page == 2): game := Game {
        width: parent.width;
        height: parent.height;

        score: root.score;
        time: root.time;
        enemy_count <=> root.enemy_count;
        game_over <=> root.game_over;
        enemy_positions <=> root.enemy_positions;

        main_char_x <=> root.main_char_x;
        main_char_y <=> root.main_char_y;
        main_char_w <=> root.main_char_w;
        main_char_h <=> root.main_char_h;

        go_to_photos => {
            root.current_page = 1;
        }

        go_to_cards => {
            root.current_page = 3;
        }

        go_to_home => {
            root.current_page = 0;
        }
    }

    Cards {
        width: parent.width;
        height: parent.height;
        visible: root.current_page == 3;

        go_to_game => {
            root.current_page = 2;
            root.navigate_to_game_with_instance();
            root.set_enemy_positions([]);
        }

        go_to_home => {
            root.current_page = 0;
        }
    }
}
