import {Background} from "background.slint";

export component Menu inherits Background {

    callback go_to_photos();
    callback go_to_game();
    callback go_to_cards();

    Text {
        text: "¡Elige uno!";
        color: #37383F;
        font-size: 70px;
        font-family: "Minecraft";
        height: parent.height * 0.90;
    }

    Rectangle {
        width: parent.width * 0.8;
        height: parent.height * 0.9;
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        clip: true;
        Image {
            width: parent.width;
            source: @image-url("../assets/img/carta.png");
        }

        VerticalLayout {
            alignment: center;
            HorizontalLayout {

                x: parent.width - self.width - parent.width * 0.05;
                alignment: center;

                spacing: parent.width * 0.14;
                padding: parent.width * 0.05;
                width: parent.width * 0.9;

                Rectangle {
                    width: root.width * 0.15;
                    height: self.width;
                    border-radius: self.width / 2;
                    background: gray;
                    border-color: black;
                    border-width: self.width * 0.05;
                    clip: true;
                    Image {
                        width: parent.width * 0.8;
                        height: parent.height * 0.6;
                        source: @image-url("../assets/img/camara.png");
                    }

                    TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => {
                            root.go_to_photos();
                        }
                    }
                }

                Rectangle {
                    width: root.width * 0.15;
                    height: self.width;
                    border-radius: self.width / 2;
                    background: gray;
                    border-color: black;
                    border-width: self.width * 0.05;
                    clip: true;
                    Image {
                        width: parent.width * 0.65;
                        height: parent.height * 0.65;
                        source: @image-url("../assets/img/dinosaur.png");
                    }

                    TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => {
                            root.go_to_game();
                        }
                    }
                }

                Rectangle {
                    width: root.width * 0.15;
                    height: self.width;
                    border-radius: self.width / 2;
                    background: gray;
                    border-color: black;
                    border-width: self.width * 0.05;
                    clip: true;
                    Image {
                        width: parent.width * 0.75;
                        height: parent.height * 0.65;
                        source: @image-url("../assets/img/cartas.png");
                    }

                    TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => {
                            root.go_to_cards();
                        }
                    }
                }
            }
        }
    }
}
