import {Background} from "background.slint";

export component Photos inherits Background {

    Text {
        text: "¡Fotos!";
        color: #37383F;
        font-size: 70px;
        font-family: "Minecraft";
        height: parent.height * 0.90;
    }

    VerticalLayout {

        padding-top: parent.height * 0.08;

        spacing: -50px;
        padding: 25px;

        HorizontalLayout {

            spacing: 20px;
            padding: 30px;
            Rectangle {
                border-color: black;
                border-width: 2px;
                border-radius: 15px;
                clip: true;
                Image {
                    source: @image-url("../assets/img/ferris.png");
                    width: parent.width;
                    height: parent.height;
                }
            }

            Rectangle {
                border-color: black;
                border-width: 2px;
                border-radius: 15px;
                clip: true;
                Image {
                    source: @image-url("../assets/img/ferris.png");
                    width: parent.width;
                    height: parent.height;
                }
            }

            Rectangle {
                border-color: black;
                border-width: 2px;
                border-radius: 15px;
                clip: true;
                Image {
                    source: @image-url("../assets/img/cuy.png");
                    width: parent.width;
                    height: parent.height;
                }
            }
        }

        HorizontalLayout {

            spacing: 20px;
            padding: 30px;

            Rectangle {
                border-color: black;
                border-width: 2px;
                border-radius: 15px;
                clip: true;
                Image {
                    source: @image-url("../assets/img/cuy.png");
                    width: parent.width;
                    height: parent.height;
                }
            }

            Rectangle {
                border-color: black;
                border-width: 2px;
                border-radius: 15px;
                clip: true;
                Image {
                    source: @image-url("../assets/img/cuy.png");
                    width: parent.width;
                    height: parent.height;
                }
            }

            Rectangle {
                border-color: black;
                border-width: 2px;
                border-radius: 15px;
                clip: true;
                Image {
                    source: @image-url("../assets/img/cuy.png");
                    width: parent.width;
                    height: parent.height;
                }
            }
        }
    }
}
